build:
    cache:
        directories:
            - vendor        # Cache for already installed composer package -> speed up composer install
            - bin           # As vendor directory is cached, bin directory must be also cached (as some dependency will not installed if they are already present and so, related binary will not be linked)
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
    environment:
        timezone: 'UTC'
        php:
            version: '8.2'
            ini:
                'date.timezone': 'UTC'
                memory_limit: -1
                max_execution_time: -1
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    paths:
        - "src/*"
    dependency_paths:
        - "vendor/"
    excluded_paths:
        - "*/tests/*"
        - "*/Tests/*"

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 1800
