language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
  - "hhvm-nightly"

branches:
  except:
    - /^draft-.*/

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

branches:
  except:
    - /^draft-.*/

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update
  - composer install --dev

script: ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls -v
