language: php
dist: trusty
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"
  - "hhvm-nightly"

branches:
  except:
    - /^draft-.*/

matrix:
  allow_failures:
    - php: "5.4"
    - php: "hhvm"
    - php: "hhvm-nightly"

branches:
  except:
    - /^draft-.*/

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls --no-update
  - composer install

script: ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls -v
