name: static-analysis

on:
    push:
        branches: [ "main" ]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    ini-values: memory_limit=-1, max_execution_time=-1, post_max_size=256M
                    tools: vimeo/psalm
                    coverage: none

            -   name: Get Composer cache directory
                id: composer-cache-dir
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer
                id: cache-composer
                uses: actions/cache@v3
                with:
                    # Use composer.json for key as composer.lock is not committed.
                    key: ${{ runner.os }}:composer-${{ hashFiles('**/composer.json') }}
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    restore-keys: |
                        ${{ runner.os }}:composer-${{ hashFiles('**/composer.json') }}
                        ${{ runner.os }}:composer-

            -   name: Cache vendor directory
                id: cache-vendor
                uses: actions/cache@v3
                with:
                    # Use composer.json for key as composer.lock is not committed.
                    key: ${{ runner.os }}:php-8.1:vendor-${{ hashFiles('**/composer.json') }}
                    path: vendor

            -   name: Install composer dependencies
                run: composer install --ansi --no-progress --optimize-autoloader

            -   name: Psalm
                run: |
                    psalm --no-progress || psalm --output-format=github --no-progress
